version: 2


aliases:
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/golang:1.12
  - &release_filter
    filters:
      tags:
        only: /.*/
      branches:
        ignore: /.*/
  - &master_filter
    filters:
      branches:
        only: master

jobs:

  build_daemon_and_cli:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build And Test Project
          command: |
            go build -o cyberd ./daemon
            go build -o cyberdcli ./cli
            go get github.com/mattn/goveralls
            go test -v -race -cover -coverprofile=./coverage.out ./...
            $GOPATH/bin/goveralls -service=circle-ci -coverprofile=./coverage.out -repotoken=$COVERALLS_TOKEN

  update_changelog:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Update Changelog
          command: |
            cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p cyberd --exclude-tags-regex .*[.].*[.].*[.].* --token $CHANGELOG_GITHUB_TOKEN )
            docker attach $cid
            docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
            diff=$(git diff CHANGELOG.md)
            if [[  -n  "$diff" ]]; then
              git config --global user.email "cybercongress42@gmail.com"
              git config --global user.name "Cyber Admin"
              git add CHANGELOG.md
              git commit -m "Circle CI: Update Changelog"
              git push --set-upstream origin master
            fi


  update_docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update Docs
          working_directory: ~/workdir
          command: |
            ./script.sh
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git
      - deploy:
          name: Update docs from cyberd repo
          working_directory: ~/workdir/congress
          command: |
            # We need to remove current files in folder to avoid duplicating renamed files
            rm -rf ./site/content/docs/cyberd/*
            cp -r ~/build/docs/. ./site/content/docs/cyberd/
            cp ~/build/CHANGELOG.md ./site/content/docs/cyberd/Changelog.md
            cp ~/build/CONTRIBUTING.md ./site/content/docs/cyberd/Contributing.md
            git add -N site/content/docs/cyberd
            diff=$(git diff site/content/docs/cyberd/)
            if [[  -n  "$diff" ]]; then
              git config user.email "cybercongress42@gmail.com"
              git config user.name "Cyber Admin"
              git add site/content/docs/cyberd/
              git commit -m "Circle CI: Update Docs"
              # Push quietly to prevent showing the token in log
              git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master
            fi


  build_and_deploy_images_to_dockerhub:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build And Deploy Cyberd Image
          command: |
            docker build -t build/cyberd .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag build/cyberd cyberd/cyberd:euler-$CIRCLE_TAG
            docker push cyberd/cyberd:euler-$CIRCLE_TAG
            docker tag build/cyberd cyberd/cyberd:euler-4
            docker push cyberd/cyberd:euler-4
          no_output_timeout: 30m


  release_cyberdcli_binaries:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Github Release Cyberd Binaries
          command: |
            go build -o cyberdcli ./cli
            sudo apt-get update && sudo apt-get install -y rpm
            curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  cyberd_build:
    jobs:
      - build_daemon_and_cli:
          filters:
            tags:
              only: /.*/
      - update_changelog:
          <<: *master_filter
          requires:
            - build_daemon_and_cli
      - update_docs:
          <<: *master_filter
          requires:
            - build_daemon_and_cli
      - build_and_deploy_images_to_dockerhub:
          <<: *release_filter
          requires:
            - build_daemon_and_cli
      - release_cyberdcli_binaries:
          <<: *release_filter
          requires:
            - build_daemon_and_cli
